### PR TITLE
Additional cluster creation requirements

### PR DESCRIPTION
**Pull request by yghazoua**
Add tags to a cluster
Specify a different resource group for the worker nodes subnet than the one from the cluster

### CODE REVIEW

**Comment by xaaaaav** [comment]
Bumping this. Tagging I see becoming more and more important. Especially for customers looking for a chargeback model. @hrjn @JedIV

**Comment by hrjn** [comment]
Seems like:
> Specify a different resource group for the worker nodes subnet than the one from the cluster

is a duplicate of #23 so let's keep things simple, use #20  PR just for the tagging stuff and remove the rest of the code

@yghazoua do you mind fixing the conflicts + doing this so that the PR can be properly reviewed + verified ? Thx !

**Comment by hrjn** [comment]
Also while we are at tagging, it seems that this PR only covers *cluster tagging*: would it be possible to go even deeper and tag all "individual" resources (e.g. nodes) created? Maybe it's done automatically by cluster tagging, I honestly don't know 🙂  But if the rationale is about building a chargeback model, maybe just tagging clusters won't be enough

**Comment by xaaaaav** [comment]
Yes, we should try to do cluster and nodes. The way I have been presenting chargeback is use tagging on all resources - including node groups and use kubernetes labels and nodeSelectors to force different groups workloads on to the nodes tagged for those groups (i.e. finance is doing some work and all their containers are going to the node pool with labels group=finance).

**Comment by duckie** [comment]
Implemented in 2.0 by #30

**Pull request closed without merging**
