### PR TITLE
Update Nvidia plugin to use latest version

### PR DESCRIPTION
**Pull request by vrutz**
Nvidia switched from master to main. We are currently using an outdated version of the plugin.

### CODE REVIEW

**Comment by vrutz** [comment]
Pending completion of PR for EKS plugin: https://github.com/dataiku/dss-plugin-eks-clusters/pull/58

**Comment by vrutz** [comment]
Integration tests were run on EKS with the previous version of the driver successfully: https://qa-jenkins.dku.sh/job/dip-on-demand/1655 (Note the two tests that fail due to a timeout)
And the tests were run again with the version on master and we get similar results: 
image

**Comment by vrutz** [comment]
Integration tests were run on EKS with the previous version of the driver successfully: https://qa-jenkins.dku.sh/job/dip-on-demand/1655 (Note the two tests that fail due to a timeout)
And the tests were run again with the version on master and we get similar results:
image

**Review by amandineslx — APPROVED** [review]
OK for me

* same change as for EKS plugin
* integration tests were run successfully on instance with new version of EKS plugin containing this change

**Pull request merged**
