### PR TITLE
1.1.0 tentative improvements

### PR DESCRIPTION
**Pull request by hrjn**
- [x] Better handling of encoding errors when dealing with stuff like [this](https://github.com/Azure/azure-cli/issues/12207). Should be fixed in `msrestazure==0.6.4`, best way is to check with a classic "exhausted-quota" error :trollface: 
- [x] Add taints on a nodepool (parameter-set)
- [ ] Create new nodepool with taints (runnable)
- [x] New icon (issue #6 )
- [ ] Advanced: custom yaml/json-based configuration (similar to GKE and EKS plugins)
- [ ] Advanced: custom name for nodeResourceGroup (issue #9 )
- [ ] Explicit naming for additional nodepools (runnable)

### CODE REVIEW

**Comment by alexcombessie** [comment]
Thanks @hrjn. Small thing on the new icon, it's missing a space to separate with icon-cloud (fallback).

**Comment by alexcombessie** [comment]
Thanks @hrjn for including the new icon. Should it also be in the python-clusters and python-runnables JSON files ?

**Comment by adescamps** [comment]
>Better handling of encoding errors when dealing with stuff like this. Should be fixed in msrestazure==0.6.4, best way is to check with a classic "exhausted-quota" error :trollface:

Nope, I tried and they still don't get it right. I pushed a PR to fix it, waiting for them to review...

**Comment by hrjn** [comment]
Closing this PR for now as several of its items will be (or already have been) handled individually somewhere else.

**Pull request closed without merging**
