### PR TITLE
Allow for agent pool mode selection

### LINKED ISSUE #11: Let users choose nodegroup mode
Nodegroup mode can be `System` or `User`. We should let the users select theur preferred mode.

At least one "system" nodegroup is required.

### PR DESCRIPTION
**Pull request by LoicAG**
Fixes #11 

@duckie can you please take a look at this PR, as well as my other one?

### CODE REVIEW

**Review by hrjn — CHANGES_REQUESTED** [review]
@LoicAG there are a few conflicts probably resulting from the merge of the previous PR. Also, while reading the [AKS documentation](https://docs.microsoft.com/en-us/azure/aks/use-system-pools), I saw that to fully prevent application pods from being scheduled on system nodes, adding the `CriticalAddonsOnly=true:NoSchedule` taint on the system nodepool(s) is essential. If such a clear separation between system and user workloads is indeed the main goal of your contribution, it would be important to have that implemented, probably as an option (i.e. a `BOOLEAN` parameter enabled by default) to leave some flexibility to the user. 

Do you think it's something you can add? Thanks 🙂

**Comment by LoicAG** [comment]
Hi, thanks for the review!

Regarding conflicts: it was indeed due to the previous merge, I've fixed them.

Regarding the taint: my main goal here is actually not to run user workloads on `User` nodes only, but rather to save costs with a set-up like this
- a `System` node pool with exactly 1 node (which is the minimum required by AKS) on a relatively small VM, and
- a `User` node pool with 0 to N nodes, with AKS auto-scaling enabled, on bigger VMs

Since it doesn't conflict your suggestion to allow users to add the `CriticalAddonsOnly=true:NoSchedule` taint on the `System` node pools, I'll add the option as well, but I'd rather leave it off by default if that's all right with you.

WDYT?

**Review by hrjn — APPROVED** [review]
Looking good. Thanks for the contribution !

**Comment by LoicAG** [comment]
Glad I could help! While you're there, could you also take a look at my third (and final) PR? It's mostly cosmetic / organizational : https://github.com/dataiku/dss-plugin-aks-clusters/pull/23

**Comment by hrjn** [comment]
Sure, I'll review it in the upcoming days.

**Pull request merged**
